### ISSUE TITLE
Bundle and Export command not appearing on v12

### ISSUE THREAD

**Issue by flyingsquad** [dmarcuse/fvtt-adventure-bundler#13]
I updated a copy of my Foundry installation to v12 and the Bundle and Export command is not displayed when I right-click an adventure in a compendium. The menu includes only the Rebuild Adventure and Delete Entry commands. The import bundle button is still present in the compendium window.

No errors are displayed in the browser debug console, just the message for for loading en.json.

Without the Bundle and Export feature the bundler is useless.

**Comment by dmarcuse** [comment]
Please double check that you've updated your modules, this issue was fixed in v0.2.4. If you've already updated to v0.2.4 and are still encountering this issue, let me know what Foundry version, system, and other modules you're using and I'll re-open the issue.

**Comment by flyingsquad** [comment]
Yeah, I'm using 0.2.4 and Foundry version 12 release 331. I disabled all modules except Tidy UI and the Bundle and Export command is still not displaying when I right-click an adventure in a compendium. Also using DnD 5e 3.3.1, though I doubt that makes any difference.
I really like this module because it lets me develop my adventures on my home computer and then upload the .zip files to Molten quickly and easily. It works great for me on v11, and I don't want to update to version 12 until it's good to go.
Thanks for doing all the work on it!

**Comment by dmarcuse** [comment]
Hmm, that's interesting. I'll have to experiment more, but with some quick testing I'm not able to reproduce the issue. I host Foundry myself, so I don't know whether Molten is affecting this.

If you have the time, could you do some extra tests for me?

- Could you try the module in a fresh world using the Pathfinder 2e system? That's what I use most, and seems to work for me.
- After opening the world and right clicking an adventure in a compendium, if you open your browser's developer console and press F12, do you see any errors, lines highlighted in red?
- Could you try installing Foundry V12 on your home computer and testing the module there? You'll want to back up your data folder first, so you can restore it and go back to V11 afterwards.

**Comment by flyingsquad** [comment]
Well, this is getting annoying. I have two v12 installations: one on my "development" machine and one on an externally visible mini-PC that I'm setting up to host. The bundler works on the development installation of Foundry, but not on the externally visible host (which is a copy of the Molten system, but updated to v12.331 and DnD 3.3.1).

I haven't updated Molten (because all the modules I use aren't completely updated yet for v12).

It also works in PF2, and several other DnD worlds on the same machine. Something about certain worlds is inhibiting that one command. It may have something to do with having converted a v11 world to v12.

What was the fix you made to restore that command? Might there be something about updating a world that may have caused that bug to resurface?

**Comment by flyingsquad** [comment]
Okay, I found the problem by looking at the console log (which I should have done immediately, sorry!). There was some interaction with multiple document selection. When I disabled that it works again. 

Not sure why I still got the error when I disabled all the other modules.

Thanks again for all your work!

**Comment by dmarcuse** [comment]
Glad to hear it's working!
