### ISSUE TITLE
When adding items and actors a system has to be specified

### ISSUE THREAD

**Issue by klenkes74** [dmarcuse/fvtt-adventure-bundler#4]
I can't add items and actors to the adventure since then a system has to be specified. I did not find a way to specify a system - but it should be the same system the world I'm using to export is running as.

**Comment by dmarcuse** [comment]
If you're referring to the adventure building dialog, that's handled by Foundry itself and there's not a lot I can do about it - this module just handles the export/import buttons for once you have an adventure created. Could you share more details and/or screenshots of what exactly you're trying to do?

**Comment by klenkes74** [comment]
I tried to reproduce it again today and failed. Yesterday I got the error message all the time but Today everything works. Don't know what I did yesterday - sorry.

**Comment by dmarcuse** [comment]
Classic case of ephemeral tech gremlins I suppose, thanks for the update!
